# Generated by Django 3.2.9 on 2022-06-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POLICE', '0004_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='finish_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='week_number',
            field=models.CharField(blank=True, editable=False, max_length=2),
        ),
    ]
