# Generated by Django 3.2.9 on 2022-06-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POLICE', '0005_auto_20220612_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='start_date',
            field=models.DateField(),
        ),
    ]
